import turtle
my_turtle = turtle.Turtle()
window = turtle.Screen()
length = 50
my_turtle.shape("turtle")
my_turtle.color("purple")
my_turtle.forward(length)
my_turtle.left(90)
my_turtle.forward(length)
my_turtle.left(90)
my_turtle.forward(length)
my_turtle.left(90)
my_turtle.forward(length)

my_turtle.up()
my_turtle.color("red")
my_turtle.forward(20)
my_turtle.down()
my_turtle.forward(length)
my_turtle.left(90)
my_turtle.forward(length)
my_turtle.left(90)
my_turtle.forward(length)
my_turtle.left(90)
my_turtle.forward(length)
window.exitonclick()